package at.ac.tuwien.infosys.aic10.ass2.process;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.3
 * Fri Jan 14 12:10:01 CET 2011
 * Generated source version: 2.2.3
 * 
 */
 
@WebService(targetNamespace = "http://infosys.tuwien.ac.at/aic10/ass2/process", name = "OrderProcessPortType")
@XmlSeeAlso({at.ac.tuwien.infosys.aic10.ass2.orderprocessschema.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface OrderProcessPortType {

    @WebResult(name = "result", targetNamespace = "http://infosys.tuwien.ac.at/aic10/ass2/OrderProcessSchema", partName = "part1")
    @WebMethod(operationName = "start_process")
    public at.ac.tuwien.infosys.aic10.ass2.orderprocessschema.Result startProcess(
        @WebParam(partName = "part1", name = "parameters", targetNamespace = "http://infosys.tuwien.ac.at/aic10/ass2/OrderProcessSchema")
        at.ac.tuwien.infosys.aic10.ass2.orderprocessschema.Parameters part1
    );

    @WebResult(name = "callback_result", targetNamespace = "http://infosys.tuwien.ac.at/aic10/ass2/OrderProcessSchema", partName = "part1")
    @WebMethod
    public at.ac.tuwien.infosys.aic10.ass2.orderprocessschema.CallbackResult callback(
        @WebParam(partName = "part1", name = "parameters_callback", targetNamespace = "http://infosys.tuwien.ac.at/aic10/ass2/OrderProcessSchema")
        at.ac.tuwien.infosys.aic10.ass2.orderprocessschema.ParametersCallback part1
    );
}
